steps:
  # 1. Build backend Docker image (simplified without caching for now)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '$_AR_HOSTNAME/$PROJECT_ID/ai-storytime-backend/$_BACKEND_SERVICE_NAME:latest',
      '--file', 'Dockerfile.backend',
      '.'
    ]

  # 2. Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '$_AR_HOSTNAME/$PROJECT_ID/ai-storytime-backend/$_BACKEND_SERVICE_NAME:latest'
    ]

  # 3. Deploy to Cloud Run with mobile-optimized settings
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_BACKEND_SERVICE_NAME'
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/ai-storytime-backend/$_BACKEND_SERVICE_NAME:latest'
      - '--region'
      - '$_DEPLOY_REGION'
      - '--platform'
      - 'managed'
      - '--port'
      - '3000'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '600'
      - '--concurrency'
      - '10'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,GCS_IMAGES_BUCKET_NAME=storytime-images-1768-sydney,GCS_PDFS_BUCKET_NAME=storytime-pdfs-1768-sydney,IMAGE_GENERATION_SERVICE=GOOGLE_IMAGEN,STORY_PAGES_COUNT=23,BASE_CURRENCY=aud,STORY_TEASER_PAGES_COUNT=7,CREDITS_PER_BASE_CURRENCY=1,IMAGE_GENERATION_DELAY_MS=15000,STORY_REF_CONCURRENCY=2,STORY_IMAGE_CONCURRENCY=25,ALLOW_DEV_LOGIN=false,PRINT_MIN_PAGES=10,PRINT_PAGE_COST=4,PRINT_SHIPPING_COST=10,MOBILE_MODE=true'
      - '--set-secrets'
      - 'MONGODB_URI=MONGODB_URI:latest,STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest,STRIPE_WEBHOOK_SECRET=STRIPE_WEBHOOK_SECRET:latest,AUTH_SECRET=AUTH_SECRET:latest,SMTP_PASSWORD=SMTP_PASSWORD:latest,MISTRAL_API_KEY=MISTRAL_API_KEY:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,APP_URL=APP_URL:latest,SMTP_USER=SMTP_USER:latest,GELATO_API_KEY=GELATO_API_KEY:latest,GELATO_TEST_MODE=GELATO_TEST_MODE:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest,GOOGLE_API_KEY_P=GOOGLE_API_KEY_P:latest'

  # 4. Deploy backend to Cloud Run with mobile-optimized settings
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_BACKEND_SERVICE_NAME'
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/ai-storytime-backend/$_BACKEND_SERVICE_NAME:latest'
      - '--region'
      - '$_DEPLOY_REGION'
      - '--platform'
      - 'managed'
      - '--port'
      - '3000'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '600'
      - '--concurrency'
      - '10'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,GCS_IMAGES_BUCKET_NAME=storytime-images-1768-sydney,GCS_PDFS_BUCKET_NAME=storytime-pdfs-1768-sydney,IMAGE_GENERATION_SERVICE=GOOGLE_IMAGEN,STORY_PAGES_COUNT=23,BASE_CURRENCY=aud,STORY_TEASER_PAGES_COUNT=7,CREDITS_PER_BASE_CURRENCY=1,IMAGE_GENERATION_DELAY_MS=15000,STORY_REF_CONCURRENCY=2,STORY_IMAGE_CONCURRENCY=25,ALLOW_DEV_LOGIN=false,PRINT_MIN_PAGES=10,PRINT_PAGE_COST=4,PRINT_SHIPPING_COST=10,MOBILE_MODE=true'
      - '--set-secrets'
      - 'MONGODB_URI=MONGODB_URI:latest,STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest,STRIPE_WEBHOOK_SECRET=STRIPE_WEBHOOK_SECRET:latest,AUTH_SECRET=AUTH_SECRET:latest,SMTP_PASSWORD=SMTP_PASSWORD:latest,MISTRAL_API_KEY=MISTRAL_API_KEY:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,APP_URL=APP_URL:latest,SMTP_USER=SMTP_USER:latest,GELATO_API_KEY=GELATO_API_KEY:latest,GELATO_TEST_MODE=GELATO_TEST_MODE:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest,GOOGLE_API_KEY_P=GOOGLE_API_KEY_P:latest'

substitutions:
  _DEPLOY_REGION: australia-southeast1
  _AR_HOSTNAME: australia-southeast1-docker.pkg.dev
  _BACKEND_SERVICE_NAME: storytime-backend