steps:
  # 1. Build and push the Docker image using BuildKit and registry cache
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker buildx create --use --driver docker-container
        docker buildx build \
          --cache-from=type=registry,ref=$_AR_HOSTNAME/$PROJECT_ID/ai-storytime-backend/$_BACKEND_SERVICE_NAME:buildcache \
          --cache-to=type=registry,ref=$_AR_HOSTNAME/$PROJECT_ID/ai-storytime-backend/$_BACKEND_SERVICE_NAME:buildcache,mode=max \
          -t $_AR_HOSTNAME/$PROJECT_ID/ai-storytime-backend/$_BACKEND_SERVICE_NAME:latest \
          --file Dockerfile.backend \
          --build-arg VITE_REVIEWER_BOOK_ID=$_VITE_REVIEWER_BOOK_ID \
          --build-arg VITE_STORY_TEASER_PAGES_COUNT=$_VITE_STORY_TEASER_PAGES_COUNT \
          --build-arg VITE_STORY_COST=$_VITE_STORY_COST \
          --build-arg VITE_IMAGE_COST=$_VITE_IMAGE_COST \
          --build-arg VITE_PDF_COST=$_VITE_PDF_COST \
          --build-arg VITE_PRINT_PRICE=$_VITE_PRINT_PRICE \
          --build-arg VITE_BASE_CURRENCY=$_VITE_BASE_CURRENCY \
          --build-arg VITE_GOOGLE_CLIENT_ID=$_VITE_GOOGLE_CLIENT_ID \
          --push \
          .

  # 2. Deploy to Cloud Run with mobile-optimized settings and debug logging
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_BACKEND_SERVICE_NAME'
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/ai-storytime-backend/$_BACKEND_SERVICE_NAME:latest'
      - '--region'
      - '$_DEPLOY_REGION'
      - '--platform'
      - 'managed'
      - '--port'
      - '3001'
      - '--memory'
      - '8Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '600'
      - '--concurrency'
      - '10'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '4'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,LOG_LEVEL=debug,GCP_PROJECT_ID=$PROJECT_ID,GCS_IMAGES_BUCKET_NAME=storytime-images-1768-sydney,GCS_PDFS_BUCKET_NAME=storytime-pdfs-1768-sydney,IMAGE_GENERATION_SERVICE=GOOGLE_IMAGEN,STORY_PAGES_COUNT=23,BASE_CURRENCY=usd,STORY_TEASER_PAGES_COUNT=7,CREDITS_PER_BASE_CURRENCY=1,IMAGE_GENERATION_DELAY_MS=15000,STORY_REF_CONCURRENCY=2,STORY_IMAGE_CONCURRENCY=30,ALLOW_DEV_LOGIN=false,PRINT_MIN_PAGES=28,PRINT_PAGE_COST=2,PRINT_SHIPPING_COST=10,MOBILE_MODE=true,PRINT_PRICE_AMOUNT=4999,MONGODB_DB_NAME=story-db'
      - '--set-secrets'
      - 'MONGODB_URI=MONGODB_URI:latest,STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest,STRIPE_WEBHOOK_SECRET=STRIPE_WEBHOOK_SECRET:latest,AUTH_SECRET=AUTH_SECRET:latest,SMTP_PASSWORD=SMTP_PASSWORD:latest,MISTRAL_API_KEY=MISTRAL_API_KEY:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,APP_URL=APP_URL:latest,SMTP_USER=SMTP_USER:latest,GELATO_API_KEY=GELATO_API_KEY:latest,GELATO_TEST_MODE=GELATO_TEST_MODE:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest,GOOGLE_API_KEY_P=GOOGLE_API_KEY_P:latest'

substitutions:
  _DEPLOY_REGION: australia-southeast1
  _AR_HOSTNAME: australia-southeast1-docker.pkg.dev
  _BACKEND_SERVICE_NAME: storytime-backend
  _VITE_REVIEWER_BOOK_ID: "697736eadd2afbb4f929b2ff"
  _VITE_STORY_TEASER_PAGES_COUNT: "7"
  _VITE_STORY_COST: "10"
  _VITE_IMAGE_COST: "2"
  _VITE_PDF_COST: "9.99"
  _VITE_PRINT_PRICE: "49.99"
  _VITE_BASE_CURRENCY: "usd"
  _VITE_GOOGLE_CLIENT_ID: "959069445137-v0v6jrreojcrclbi6skclrvgn6dr6vgs.apps.googleusercontent.com"
